package modelo.entidades;
// default package
// Generated 2 feb. 2021 13:38:13 by Hibernate Tools 5.2.12.Final

import java.time.LocalDate;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	private String nombre;
	private String apellidos;
	private Date fechaNacimiento;
	private Set prestamos = new HashSet(0);
	private Contactousuario contactousuario;

	public Usuario() {
	}

	public Usuario(String nombre, String apellidos, Date fechaNacimiento) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.fechaNacimiento = fechaNacimiento;
	}

	public Usuario(String nombre, String apellidos, Date fechaNacimiento, Set prestamos,
			Contactousuario contactousuario) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.fechaNacimiento = fechaNacimiento;
		this.prestamos = prestamos;
		this.contactousuario = contactousuario;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public Set getPrestamos() {
		return this.prestamos;
	}

	public void setPrestamos(Set prestamos) {
		this.prestamos = prestamos;
	}

	public Contactousuario getContactousuario() {
		return this.contactousuario;
	}

	public void setContactousuario(Contactousuario contactousuario) {
		this.contactousuario = contactousuario;
	}

}
