package modelo.entidades;
// default package
// Generated 2 feb. 2021 13:38:13 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idUsuario;
	private String nombre;
	private String apellidos;
	private Date fechaNacimiento;
	private String Dni;
	private Set<Prestamo> prestamos = new HashSet<Prestamo>(0);
	private Contactousuario contactousuario;
	
	public Usuario() {
		
	}

	public Usuario(String nombre, String apellidos, Date fechaNacimiento, String Dni) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.fechaNacimiento = fechaNacimiento;
		this.Dni = Dni;
	}

	public Usuario(String nombre, String apellidos, Date fechaNacimiento, Set<Prestamo> prestamos, Contactousuario contactousuario) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.fechaNacimiento = fechaNacimiento;
		this.prestamos = prestamos;
		this.contactousuario = contactousuario;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getDni() {
		return Dni;
	}

	public void setDni(String dni) {
		Dni = dni;
	}
	
	public Set<Prestamo> getPrestamos() {
		return this.prestamos;
	}

	public void setPrestamos(Set<Prestamo> prestamos) {
		this.prestamos = prestamos;
	}

	public Contactousuario getContactousuario() {
		return this.contactousuario;
	}

	public void setContactousuario(Contactousuario contactousuario) {
		this.contactousuario = contactousuario;
	}

	@Override
	public String toString() {
		return "Usuario [idUsuario=" + idUsuario + ", nombre=" + nombre + ", apellidos=" + apellidos
				+ ", fechaNacimiento=" + fechaNacimiento + ", Dni=" + Dni + ", prestamos=" + prestamos
				+ ", contactousuario=" + contactousuario + "]";
	}

}
